# Generated by Django 5.0.6 on 2024-06-11 16:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productbasket_productbasket_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
