# Generated by Django 5.0.6 on 2024-06-15 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_product_description_product_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='product',
            name='ingredients',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
