# Generated by Django 5.0.6 on 2024-06-22 19:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_productreviewlike_review_productreviewlike_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='productreviewlike',
            constraint=models.UniqueConstraint(fields=('review', 'user'), name='review_like__constraint'),
        ),
    ]
