# Generated by Django 5.0.6 on 2024-06-26 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_basketarchive_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketarchive',
            name='data',
            field=models.JSONField(default=dict),
        ),
    ]
