# Generated by Django 5.0.6 on 2024-08-02 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_alter_basketarchive_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='basket',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='basket', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='basket',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('owner', 'status'), name='basket_status_active_unique_constraint'),
        ),
    ]
