# Generated by Django 5.0.6 on 2024-06-28 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='publicated_at',
            field=models.DateTimeField(default='2016-10-03T19:00:00+0200'),
            preserve_default=False,
        ),
    ]
