# Generated by Django 5.0.6 on 2024-06-28 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_rename_message_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
