# Generated by Django 5.0.6 on 2024-07-21 11:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chatmessage_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chat_media/'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='publicated_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
