# Generated by Django 5.0.6 on 2024-07-22 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_chatmessage_image_alter_chatmessage_publicated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='deleted',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
