# Generated by Django 5.0.6 on 2024-07-26 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_chatimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='image',
        ),
    ]
