# Generated by Django 5.0.6 on 2024-08-03 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friends', models.ManyToManyField(through='social_network.Friendship', to='social_network.profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='social_network_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='friendship',
            name='friend_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_1', to='social_network.profile'),
        ),
        migrations.AddField(
            model_name='friendship',
            name='friend_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_2', to='social_network.profile'),
        ),
        migrations.AddConstraint(
            model_name='friendship',
            constraint=models.UniqueConstraint(fields=('friend_1', 'friend_2'), name='friendship_unique_constraint'),
        ),
        migrations.AddConstraint(
            model_name='friendship',
            constraint=models.CheckConstraint(check=models.Q(('friend_1', models.F('friend_2')), _negated=True), name='friendship_themselves_constraint'),
        ),
    ]
