# Generated by Django 5.0.6 on 2024-08-03 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendshipRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_profile', to='social_network.profile')),
                ('to_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_profile', to='social_network.profile')),
            ],
        ),
        migrations.AddConstraint(
            model_name='friendshiprequest',
            constraint=models.UniqueConstraint(fields=('from_profile', 'to_profile'), name='friendshiprequest_unique_constraint'),
        ),
        migrations.AddConstraint(
            model_name='friendshiprequest',
            constraint=models.CheckConstraint(check=models.Q(('from_profile', models.F('to_profile')), _negated=True), name='friendshiprequest_themselves_constraint'),
        ),
    ]
