# Generated by Django 5.0.6 on 2024-08-03 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0002_friendshiprequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendshiprequest',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='ACTIVE', max_length=20),
            preserve_default=False,
        ),
    ]
