# Generated by Django 5.0.6 on 2024-08-04 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0006_publication_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=200)),
                ('url', models.URLField()),
                ('to_profile', models.ManyToManyField(related_name='notifications', to='social_network.profile')),
            ],
        ),
    ]
