# Generated by Django 5.0.6 on 2024-08-07 19:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0007_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='text',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(1, 'the field must contain at least 10 character')]),
        ),
        migrations.AddConstraint(
            model_name='publication',
            constraint=models.CheckConstraint(check=models.Q(('text__length__gte', 1)), name='text_min_length'),
        ),
    ]
