# Generated by Django 5.0.6 on 2024-08-16 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0008_alter_publication_text_publication_text_min_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CommunityMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OWNER', 'Owner'), ('ADMIN', 'Admin'), ('READER', 'Reader'), ('WRITER', 'Writer')], max_length=50)),
                ('ban_until', models.DateTimeField(blank=True, null=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_network.community')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_network.profile')),
            ],
        ),
        migrations.AddField(
            model_name='community',
            name='members',
            field=models.ManyToManyField(through='social_network.CommunityMember', to='social_network.profile'),
        ),
    ]
