# Generated by Django 5.0.6 on 2024-08-16 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0009_community_communitymember_community_members'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='communitymember',
            constraint=models.UniqueConstraint(fields=('community', 'profile'), name='communitymember_unique_constraint'),
        ),
        migrations.AddConstraint(
            model_name='communitymember',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'OWNER')), fields=('community',), name='communitymember_owner_unique_constraint'),
        ),
    ]
