# Generated by Django 5.0.6 on 2024-08-17 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0010_communitymember_communitymember_unique_constraint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitymember',
            name='status',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('ADMIN', 'Admin'), ('READER', 'Reader'), ('WRITER', 'Writer')], default='WRITER', max_length=50),
        ),
    ]
