# Generated by Django 5.0.6 on 2024-08-17 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0011_alter_communitymember_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=2000)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_network.community')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_network.profile')),
            ],
        ),
    ]
