# Generated by Django 5.0.6 on 2024-08-17 13:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0012_communitypublication'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitypublication',
            name='publicated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
